version: '3.6'

services:
  db:
    container_name: db
    image: mariadb
    restart: always
    networks:
      - zoneminder
    volumes:
      - ./zm/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=zm
    env_file:
      - ./.env

  zoneminder:
    container_name: zoneminder
    image: ci:latest
    # Disable automatic restarts so we know if container dies on startup
    deploy:
      restart_policy:
        condition: none
    # Make grace period extremely long so test fails if
    # container doesn't automatically terminate
    stop_grace_period: 1h
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - zoneminder
    volumes:
      - ./zm/data:/data
      - ./zm/config:/config
      - ./zm/log:/log
    env_file:
      - ./.env
    environment:
      - ZM_SERVER_HOST=zoneminder1

networks:
  zoneminder:
